# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project_project_status_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_alt',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
    ]
