# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_image_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_finished',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
            preserve_default=False,
        ),
    ]
