# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_post_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_knowledge',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
            preserve_default=False,
        ),
    ]
